/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AuctionMarketInterface extends Interface {
    getFunction(nameOrSignature: "NATIVE_TOKEN" | "UPGRADE_INTERFACE_VERSION" | "USD_DECIMALS" | "auctionCount" | "auctions" | "bidWithEth" | "bidWithToken" | "createAuction" | "endAuction" | "initialize" | "onERC721Received" | "owner" | "paymentTokens" | "proxiableUUID" | "quoteBidUsd" | "renounceOwnership" | "setPaymentToken" | "transferOwnership" | "upgradeToAndCall"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionCreated" | "AuctionEnded" | "BidPlaced" | "Initialized" | "OwnershipTransferred" | "PaymentTokenUpdated" | "Upgraded"): EventFragment;

    encodeFunctionData(functionFragment: 'NATIVE_TOKEN', values?: undefined): string;
encodeFunctionData(functionFragment: 'UPGRADE_INTERFACE_VERSION', values?: undefined): string;
encodeFunctionData(functionFragment: 'USD_DECIMALS', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'bidWithEth', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'bidWithToken', values: [BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createAuction', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'endAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'onERC721Received', values: [AddressLike, AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentTokens', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'proxiableUUID', values?: undefined): string;
encodeFunctionData(functionFragment: 'quoteBidUsd', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPaymentToken', values: [AddressLike, AddressLike, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'upgradeToAndCall', values: [AddressLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'NATIVE_TOKEN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'UPGRADE_INTERFACE_VERSION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'USD_DECIMALS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bidWithEth', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bidWithToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'onERC721Received', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proxiableUUID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quoteBidUsd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPaymentToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'upgradeToAndCall', data: BytesLike): Result;
  }

  
    export namespace AuctionCreatedEvent {
      export type InputTuple = [auctionId: BigNumberish, seller: AddressLike, nft: AddressLike, tokenId: BigNumberish];
      export type OutputTuple = [auctionId: bigint, seller: string, nft: string, tokenId: bigint];
      export interface OutputObject {auctionId: bigint, seller: string, nft: string, tokenId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionEndedEvent {
      export type InputTuple = [auctionId: BigNumberish, winner: AddressLike, paymentToken: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, winner: string, paymentToken: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, winner: string, paymentToken: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike, paymentToken: AddressLike, amount: BigNumberish, amountUsd: BigNumberish];
      export type OutputTuple = [auctionId: bigint, bidder: string, paymentToken: string, amount: bigint, amountUsd: bigint];
      export interface OutputObject {auctionId: bigint, bidder: string, paymentToken: string, amount: bigint, amountUsd: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentTokenUpdatedEvent {
      export type InputTuple = [token: AddressLike, feed: AddressLike, tokenDecimals: BigNumberish, enabled: boolean];
      export type OutputTuple = [token: string, feed: string, tokenDecimals: bigint, enabled: boolean];
      export interface OutputObject {token: string, feed: string, tokenDecimals: bigint, enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpgradedEvent {
      export type InputTuple = [implementation: AddressLike];
      export type OutputTuple = [implementation: string];
      export interface OutputObject {implementation: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AuctionMarket extends BaseContract {
    
    connect(runner?: ContractRunner | null): AuctionMarket;
    waitForDeployment(): Promise<this>;

    interface: AuctionMarketInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    NATIVE_TOKEN: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    UPGRADE_INTERFACE_VERSION: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    USD_DECIMALS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    auctionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    auctions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, boolean, string, string, bigint, bigint] & {seller: string, nft: string, tokenId: bigint, endTime: bigint, ended: boolean, highestBidder: string, paymentToken: string, highestBid: bigint, highestBidUsd: bigint }],
      'view'
    >
    

    
    bidWithEth: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    bidWithToken: TypedContractMethod<
      [auctionId: BigNumberish, token: AddressLike, amount: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    createAuction: TypedContractMethod<
      [nft: AddressLike, tokenId: BigNumberish, duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    endAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    initialize: TypedContractMethod<
      [initialOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    onERC721Received: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paymentTokens: TypedContractMethod<
      [token: AddressLike, ],
      [[string, bigint, boolean] & {feed: string, tokenDecimals: bigint, enabled: boolean }],
      'view'
    >
    

    
    proxiableUUID: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    quoteBidUsd: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPaymentToken: TypedContractMethod<
      [token: AddressLike, feed: AddressLike, tokenDecimals: BigNumberish, enabled: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    upgradeToAndCall: TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'NATIVE_TOKEN'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'UPGRADE_INTERFACE_VERSION'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'USD_DECIMALS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'auctionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'auctions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, boolean, string, string, bigint, bigint] & {seller: string, nft: string, tokenId: bigint, endTime: bigint, ended: boolean, highestBidder: string, paymentToken: string, highestBid: bigint, highestBidUsd: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'bidWithEth'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'bidWithToken'): TypedContractMethod<
      [auctionId: BigNumberish, token: AddressLike, amount: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'createAuction'): TypedContractMethod<
      [nft: AddressLike, tokenId: BigNumberish, duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'endAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [initialOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'onERC721Received'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paymentTokens'): TypedContractMethod<
      [token: AddressLike, ],
      [[string, bigint, boolean] & {feed: string, tokenDecimals: bigint, enabled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'proxiableUUID'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'quoteBidUsd'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPaymentToken'): TypedContractMethod<
      [token: AddressLike, feed: AddressLike, tokenDecimals: BigNumberish, enabled: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'upgradeToAndCall'): TypedContractMethod<
      [newImplementation: AddressLike, data: BytesLike, ],
      [void],
      'payable'
    >;

    getEvent(key: 'AuctionCreated'): TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
getEvent(key: 'AuctionEnded'): TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PaymentTokenUpdated'): TypedContractEvent<PaymentTokenUpdatedEvent.InputTuple, PaymentTokenUpdatedEvent.OutputTuple, PaymentTokenUpdatedEvent.OutputObject>;
getEvent(key: 'Upgraded'): TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;

    filters: {
      
      'AuctionCreated(uint256,address,address,uint256)': TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
      AuctionCreated: TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
    

      'AuctionEnded(uint256,address,address,uint256)': TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
      AuctionEnded: TypedContractEvent<AuctionEndedEvent.InputTuple, AuctionEndedEvent.OutputTuple, AuctionEndedEvent.OutputObject>;
    

      'BidPlaced(uint256,address,address,uint256,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PaymentTokenUpdated(address,address,uint8,bool)': TypedContractEvent<PaymentTokenUpdatedEvent.InputTuple, PaymentTokenUpdatedEvent.OutputTuple, PaymentTokenUpdatedEvent.OutputObject>;
      PaymentTokenUpdated: TypedContractEvent<PaymentTokenUpdatedEvent.InputTuple, PaymentTokenUpdatedEvent.OutputTuple, PaymentTokenUpdatedEvent.OutputObject>;
    

      'Upgraded(address)': TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
      Upgraded: TypedContractEvent<UpgradedEvent.InputTuple, UpgradedEvent.OutputTuple, UpgradedEvent.OutputObject>;
    
    };
  }