/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AuctionMarket', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AuctionMarket__factory>
getContractFactory(name: 'AuctionMarketProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AuctionMarketProxy__factory>
getContractFactory(name: 'AuctionMarketV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AuctionMarketV2__factory>
getContractFactory(name: 'AuctionNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AuctionNFT__factory>
getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'AuctionPaymentToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AuctionPaymentToken__factory>
getContractFactory(name: 'AuctionMarketV3', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AuctionMarketV3__factory>
getContractFactory(name: 'MockV3Aggregator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockV3Aggregator__factory>

  getContractAt(name: 'AuctionMarket', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AuctionMarket>
getContractAt(name: 'AuctionMarketProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AuctionMarketProxy>
getContractAt(name: 'AuctionMarketV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AuctionMarketV2>
getContractAt(name: 'AuctionNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AuctionNFT>
getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'AuctionPaymentToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AuctionPaymentToken>
getContractAt(name: 'AuctionMarketV3', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AuctionMarketV3>
getContractAt(name: 'MockV3Aggregator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockV3Aggregator>

  deployContract(name: 'AuctionMarket', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionMarket>
deployContract(name: 'AuctionMarketProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionMarketProxy>
deployContract(name: 'AuctionMarketV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionMarketV2>
deployContract(name: 'AuctionNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionNFT>
deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'AuctionPaymentToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionPaymentToken>
deployContract(name: 'AuctionMarketV3', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionMarketV3>
deployContract(name: 'MockV3Aggregator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockV3Aggregator>

  deployContract(name: 'AuctionMarket', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionMarket>
deployContract(name: 'AuctionMarketProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionMarketProxy>
deployContract(name: 'AuctionMarketV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionMarketV2>
deployContract(name: 'AuctionNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionNFT>
deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'AuctionPaymentToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionPaymentToken>
deployContract(name: 'AuctionMarketV3', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AuctionMarketV3>
deployContract(name: 'MockV3Aggregator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockV3Aggregator>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  