/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from './mocks/index.js';
export type { mocks };
export type { AuctionMarket } from './AuctionMarket.js';
export type { AuctionMarketProxy } from './AuctionMarketProxy.js';
export type { AuctionMarketV2 } from './AuctionMarketV2.js';
export type { AuctionNFT } from './AuctionNFT.js';
export type { Counter } from './Counter.js';
export * as factories from './factories/index.js';
export { AuctionMarket__factory } from './factories/AuctionMarket__factory.js';
export { AuctionMarketProxy__factory } from './factories/AuctionMarketProxy__factory.js';
export { AuctionMarketV2__factory } from './factories/AuctionMarketV2__factory.js';
export { AuctionNFT__factory } from './factories/AuctionNFT__factory.js';
export { Counter__factory } from './factories/Counter__factory.js';
export type { MockERC20 } from './mocks/MockERC20.js';
export { MockERC20__factory } from './factories/mocks/MockERC20__factory.js';
export type { MockV3Aggregator } from './mocks/MockV3Aggregator.js';
export { MockV3Aggregator__factory } from './factories/mocks/MockV3Aggregator__factory.js';