/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20__factory } from './MockERC20__factory.js';
export { MockV3Aggregator__factory } from './MockV3Aggregator__factory.js';